# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.2.1c
maven_group = com.choicetheorem.imst
archives_name = imst
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.12
fabric_api_version = 0.102.0+1.21
neoforge_version = 21.0.167
quilt_loader_version = 0.29.0-beta.5
quilted_fabric_api_version = 11.0.0-alpha.3+0.100.7-1.21
